apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: my-namespace
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-pods
        image: mysql:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          limits:
            cpu: 200m
            memory: 800Mi
    restartPolicy: Always         # restartPolicy set to always means no matter how the pod exits, whether with an exit code 0 
                                  # or with another error exit code, it will restart. If you set it to onFailure, it will only       
                                  # restart on an failure/error exit code. If you set it to Never, it will not restart regardless
                                  # of why it exited

